// This file will be auto-generated by Supabase CLI
// Run: npm run db:generate-types to generate actual types
// For now, providing basic structure to prevent TypeScript errors

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type UserRole = 'employee' | 'manager' | 'hr' | 'accounting' | 'admin'
export type ScheduleStatus = 'draft' | 'published' | 'completed'
export type RequestStatus = 'pending' | 'approved' | 'rejected' | 'cancelled'
export type LeaveType = 'vacation' | 'sick' | 'personal' | 'emergency'
export type PayrollStatus = 'draft' | 'processing' | 'completed' | 'error'

export interface Database {
  public: {
    Tables: {
      branches: {
        Row: {
          id: string
          name: string
          address: string
          latitude: number | null
          longitude: number | null
          radius_meters: number
          timezone: string
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          address: string
          latitude?: number | null
          longitude?: number | null
          radius_meters?: number
          timezone?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          address?: string
          latitude?: number | null
          longitude?: number | null
          radius_meters?: number
          timezone?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string
          phone: string | null
          role: UserRole
          branch_id: string | null
          employee_id: string | null
          hire_date: string | null
          hourly_rate: number | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name: string
          phone?: string | null
          role?: UserRole
          branch_id?: string | null
          employee_id?: string | null
          hire_date?: string | null
          hourly_rate?: number | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string
          phone?: string | null
          role?: UserRole
          branch_id?: string | null
          employee_id?: string | null
          hire_date?: string | null
          hourly_rate?: number | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      schedules: {
        Row: {
          id: string
          employee_id: string
          branch_id: string
          shift_date: string
          start_time: string
          end_time: string
          break_minutes: number
          status: ScheduleStatus
          notes: string | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          employee_id: string
          branch_id: string
          shift_date: string
          start_time: string
          end_time: string
          break_minutes?: number
          status?: ScheduleStatus
          notes?: string | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          employee_id?: string
          branch_id?: string
          shift_date?: string
          start_time?: string
          end_time?: string
          break_minutes?: number
          status?: ScheduleStatus
          notes?: string | null
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      time_entries: {
        Row: {
          id: string
          employee_id: string
          schedule_id: string
          clock_in_time: string | null
          clock_out_time: string | null
          clock_in_location: unknown | null // POINT type
          clock_out_location: unknown | null // POINT type
          clock_in_accuracy: number | null
          clock_out_accuracy: number | null
          total_hours: number | null
          is_verified: boolean
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          employee_id: string
          schedule_id: string
          clock_in_time?: string | null
          clock_out_time?: string | null
          clock_in_location?: unknown | null
          clock_out_location?: unknown | null
          clock_in_accuracy?: number | null
          clock_out_accuracy?: number | null
          total_hours?: number | null
          is_verified?: boolean
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          employee_id?: string
          schedule_id?: string
          clock_in_time?: string | null
          clock_out_time?: string | null
          clock_in_location?: unknown | null
          clock_out_location?: unknown | null
          clock_in_accuracy?: number | null
          clock_out_accuracy?: number | null
          total_hours?: number | null
          is_verified?: boolean
          notes?: string | null
          created_at?: string
        }
      }
      time_entry_corrections: {
        Row: {
          id: string
          entry_id: string
          employee_id: string
          correction_type: 'clock_in' | 'clock_out' | 'both' | 'delete'
          requested_clock_in_time: string | null
          requested_clock_out_time: string | null
          reason: string
          supporting_evidence: string | null
          status: RequestStatus
          requested_by: string
          approved_by: string | null
          approved_at: string | null
          processing_notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          entry_id: string
          employee_id: string
          correction_type: 'clock_in' | 'clock_out' | 'both' | 'delete'
          requested_clock_in_time?: string | null
          requested_clock_out_time?: string | null
          reason: string
          supporting_evidence?: string | null
          status?: RequestStatus
          requested_by: string
          approved_by?: string | null
          approved_at?: string | null
          processing_notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          entry_id?: string
          employee_id?: string
          correction_type?: 'clock_in' | 'clock_out' | 'both' | 'delete'
          requested_clock_in_time?: string | null
          requested_clock_out_time?: string | null
          reason?: string
          supporting_evidence?: string | null
          status?: RequestStatus
          requested_by?: string
          approved_by?: string | null
          approved_at?: string | null
          processing_notes?: string | null
          created_at?: string
        }
      }
      shift_swap_requests: {
        Row: {
          id: string
          requester_id: string
          requester_schedule_id: string
          target_employee_id: string
          target_schedule_id: string
          status: RequestStatus
          reason: string | null
          approved_by: string | null
          approved_at: string | null
          rejection_reason: string | null
          created_at: string
        }
        Insert: {
          id?: string
          requester_id: string
          requester_schedule_id: string
          target_employee_id: string
          target_schedule_id: string
          status?: RequestStatus
          reason?: string | null
          approved_by?: string | null
          approved_at?: string | null
          rejection_reason?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          requester_id?: string
          requester_schedule_id?: string
          target_employee_id?: string
          target_schedule_id?: string
          status?: RequestStatus
          reason?: string | null
          approved_by?: string | null
          approved_at?: string | null
          rejection_reason?: string | null
          created_at?: string
        }
      }
      leave_requests: {
        Row: {
          id: string
          employee_id: string
          leave_type: LeaveType
          start_date: string
          end_date: string
          total_days: number
          reason: string | null
          status: RequestStatus
          approved_by: string | null
          approved_at: string | null
          rejection_reason: string | null
          created_at: string
        }
        Insert: {
          id?: string
          employee_id: string
          leave_type: LeaveType
          start_date: string
          end_date: string
          total_days: number
          reason?: string | null
          status?: RequestStatus
          approved_by?: string | null
          approved_at?: string | null
          rejection_reason?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          employee_id?: string
          leave_type?: LeaveType
          start_date?: string
          end_date?: string
          total_days?: number
          reason?: string | null
          status?: RequestStatus
          approved_by?: string | null
          approved_at?: string | null
          rejection_reason?: string | null
          created_at?: string
        }
      }
      salary_advance_requests: {
        Row: {
          id: string
          employee_id: string
          amount: number
          max_eligible_amount: number
          reason: string | null
          status: RequestStatus
          approved_by: string | null
          approved_at: string | null
          processed_by: string | null
          processed_at: string | null
          transaction_proof: string | null
          rejection_reason: string | null
          created_at: string
        }
        Insert: {
          id?: string
          employee_id: string
          amount: number
          max_eligible_amount: number
          reason?: string | null
          status?: RequestStatus
          approved_by?: string | null
          approved_at?: string | null
          processed_by?: string | null
          processed_at?: string | null
          transaction_proof?: string | null
          rejection_reason?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          employee_id?: string
          amount?: number
          max_eligible_amount?: number
          reason?: string | null
          status?: RequestStatus
          approved_by?: string | null
          approved_at?: string | null
          processed_by?: string | null
          processed_at?: string | null
          transaction_proof?: string | null
          rejection_reason?: string | null
          created_at?: string
        }
      }
      payroll_periods: {
        Row: {
          id: string
          period_start: string
          period_end: string
          cutoff_date: string
          pay_date: string
          status: PayrollStatus
          created_by: string
          processed_by: string | null
          processed_at: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          period_start: string
          period_end: string
          cutoff_date: string
          pay_date: string
          status?: PayrollStatus
          created_by: string
          processed_by?: string | null
          processed_at?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          period_start?: string
          period_end?: string
          cutoff_date?: string
          pay_date?: string
          status?: PayrollStatus
          created_by?: string
          processed_by?: string | null
          processed_at?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      payroll_entries: {
        Row: {
          id: string
          payroll_period_id: string
          employee_id: string
          regular_hours: number
          overtime_hours: number
          holiday_hours: number
          regular_rate: number
          overtime_rate: number
          holiday_rate: number
          gross_salary: number
          social_security: number
          tax_deduction: number
          salary_advances: number
          other_deductions: number
          net_salary: number
          status: PayrollStatus
          generated_at: string
          approved_by: string | null
          approved_at: string | null
          notes: string | null
        }
        Insert: {
          id?: string
          payroll_period_id: string
          employee_id: string
          regular_hours: number
          overtime_hours: number
          holiday_hours: number
          regular_rate: number
          overtime_rate: number
          holiday_rate: number
          gross_salary: number
          social_security: number
          tax_deduction: number
          salary_advances: number
          other_deductions: number
          net_salary: number
          status?: PayrollStatus
          generated_at?: string
          approved_by?: string | null
          approved_at?: string | null
          notes?: string | null
        }
        Update: {
          id?: string
          payroll_period_id?: string
          employee_id?: string
          regular_hours?: number
          overtime_hours?: number
          holiday_hours?: number
          regular_rate?: number
          overtime_rate?: number
          holiday_rate?: number
          gross_salary?: number
          social_security?: number
          tax_deduction?: number
          salary_advances?: number
          other_deductions?: number
          net_salary?: number
          status?: PayrollStatus
          generated_at?: string
          approved_by?: string | null
          approved_at?: string | null
          notes?: string | null
        }
      }
      payslips: {
        Row: {
          id: string
          payroll_entry_id: string
          employee_id: string
          payroll_period_id: string
          slip_number: string
          issued_date: string
          file_path: string | null
          is_sent: boolean
          sent_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          payroll_entry_id: string
          employee_id: string
          payroll_period_id: string
          slip_number: string
          issued_date: string
          file_path?: string | null
          is_sent?: boolean
          sent_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          payroll_entry_id?: string
          employee_id?: string
          payroll_period_id?: string
          slip_number?: string
          issued_date?: string
          file_path?: string | null
          is_sent?: boolean
          sent_at?: string | null
          created_at?: string
        }
      }
      // Add other table types as needed...
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      calculate_hours_worked: {
        Args: {
          p_clock_in_time: string
          p_clock_out_time: string
          p_break_minutes?: number
        }
        Returns: number
      }
      check_schedule_conflicts: {
        Args: {
          p_employee_id: string
          p_shift_date: string
          p_start_time: string
          p_end_time: string
          p_schedule_id?: string
        }
        Returns: boolean
      }
      calculate_max_advance_amount: {
        Args: {
          p_employee_id: string
          p_period_start?: string
          p_period_end?: string
        }
        Returns: number
      }
      calculate_payroll_for_employee: {
        Args: {
          p_employee_id: string
          p_period_start: string
          p_period_end: string
        }
        Returns: {
          regular_hours: number
          overtime_hours: number
          holiday_hours: number
          gross_salary: number
          social_security: number
          tax_deduction: number
          salary_advances: number
          net_salary: number
        }
      }
      calculate_tax_deduction: {
        Args: {
          p_gross_salary: number
          p_social_security: number
        }
        Returns: number
      }
      calculate_social_security: {
        Args: {
          p_gross_salary: number
        }
        Returns: number
      }
    }
    Enums: {
      user_role: UserRole
      schedule_status: ScheduleStatus
      request_status: RequestStatus
      leave_type_enum: LeaveType
      payroll_status: PayrollStatus
    }
  }
}